//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
    [System.SerializableAttribute()]
    public partial class AltinnFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AltinnErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AltinnExtendedErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AltinnLocalizedErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltinnErrorMessage {
            get {
                return this.AltinnErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.AltinnErrorMessageField, value) != true)) {
                    this.AltinnErrorMessageField = value;
                    this.RaisePropertyChanged("AltinnErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltinnExtendedErrorMessage {
            get {
                return this.AltinnExtendedErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.AltinnExtendedErrorMessageField, value) != true)) {
                    this.AltinnExtendedErrorMessageField = value;
                    this.RaisePropertyChanged("AltinnExtendedErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltinnLocalizedErrorMessage {
            get {
                return this.AltinnLocalizedErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.AltinnLocalizedErrorMessageField, value) != true)) {
                    this.AltinnLocalizedErrorMessageField = value;
                    this.RaisePropertyChanged("AltinnLocalizedErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorGuid {
            get {
                return this.ErrorGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorGuidField, value) != true)) {
                    this.ErrorGuidField = value;
                    this.RaisePropertyChanged("ErrorGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorID {
            get {
                return this.ErrorIDField;
            }
            set {
                if ((this.ErrorIDField.Equals(value) != true)) {
                    this.ErrorIDField = value;
                    this.RaisePropertyChanged("ErrorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserGuid {
            get {
                return this.UserGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.UserGuidField, value) != true)) {
                    this.UserGuidField = value;
                    this.RaisePropertyChanged("UserGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.altinn.no/services/Archive/ServiceOwnerArchive/2013/06", ConfigurationName="ServiceOwnerArchiveExternalStreamed.IServiceOwnerArchiveExternalStreamedBasic")]
    public interface IServiceOwnerArchiveExternalStreamedBasic {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.altinn.no/services/2009/10) of message TestRequest does not match the default value (http://www.altinn.no/services/Archive/ServiceOwnerArchive/2013/06)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/Test", ReplyAction="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.AltinnFault), Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.TestResponse Test(DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/Test", ReplyAction="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestResponse")]
        System.Threading.Tasks.Task<DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.TestResponse> TestAsync(DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.TestRequest request);
        
        // CODEGEN: Generating message contract since element name systemUserName from namespace http://www.altinn.no/services/Archive/ServiceOwnerArchive/2013/06 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/Archive/ServiceOwnerArchive/2013/06/IServiceOwnerAr" +
            "chiveExternalStreamedBasic/GetAttachmentDataStreamedBasic", ReplyAction="http://www.altinn.no/services/Archive/ServiceOwnerArchive/2013/06/IServiceOwnerAr" +
            "chiveExternalStreamedBasic/GetAttachmentDataStreamedBasicResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.AltinnFault), Action="http://www.altinn.no/services/Archive/ServiceOwnerArchive/2013/06/IServiceOwnerAr" +
            "chiveExternalStreamedBasic/GetAttachmentDataStreamedBasicAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.GetAttachmentDataStreamedBasicResponse GetAttachmentDataStreamedBasic(DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.GetAttachmentDataStreamedBasicRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/Archive/ServiceOwnerArchive/2013/06/IServiceOwnerAr" +
            "chiveExternalStreamedBasic/GetAttachmentDataStreamedBasic", ReplyAction="http://www.altinn.no/services/Archive/ServiceOwnerArchive/2013/06/IServiceOwnerAr" +
            "chiveExternalStreamedBasic/GetAttachmentDataStreamedBasicResponse")]
        System.Threading.Tasks.Task<DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.GetAttachmentDataStreamedBasicResponse> GetAttachmentDataStreamedBasicAsync(DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.GetAttachmentDataStreamedBasicRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Test", WrapperNamespace="http://www.altinn.no/services/2009/10", IsWrapped=true)]
    public partial class TestRequest {
        
        public TestRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestResponse", WrapperNamespace="http://www.altinn.no/services/2009/10", IsWrapped=true)]
    public partial class TestResponse {
        
        public TestResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAttachmentDataStreamedBasicRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAttachmentDataStreamedBasic", Namespace="http://www.altinn.no/services/Archive/ServiceOwnerArchive/2013/06", Order=0)]
        public DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.GetAttachmentDataStreamedBasicRequestBody Body;
        
        public GetAttachmentDataStreamedBasicRequest() {
        }
        
        public GetAttachmentDataStreamedBasicRequest(DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.GetAttachmentDataStreamedBasicRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/Archive/ServiceOwnerArchive/2013/06")]
    public partial class GetAttachmentDataStreamedBasicRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string systemUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string systemPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int attachmentId;
        
        public GetAttachmentDataStreamedBasicRequestBody() {
        }
        
        public GetAttachmentDataStreamedBasicRequestBody(string systemUserName, string systemPassword, int attachmentId) {
            this.systemUserName = systemUserName;
            this.systemPassword = systemPassword;
            this.attachmentId = attachmentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAttachmentDataStreamedBasicResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAttachmentDataStreamedBasicResponse", Namespace="http://www.altinn.no/services/Archive/ServiceOwnerArchive/2013/06", Order=0)]
        public DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.GetAttachmentDataStreamedBasicResponseBody Body;
        
        public GetAttachmentDataStreamedBasicResponse() {
        }
        
        public GetAttachmentDataStreamedBasicResponse(DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.GetAttachmentDataStreamedBasicResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/Archive/ServiceOwnerArchive/2013/06")]
    public partial class GetAttachmentDataStreamedBasicResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public byte[] GetAttachmentDataStreamedBasicResult;
        
        public GetAttachmentDataStreamedBasicResponseBody() {
        }
        
        public GetAttachmentDataStreamedBasicResponseBody(byte[] GetAttachmentDataStreamedBasicResult) {
            this.GetAttachmentDataStreamedBasicResult = GetAttachmentDataStreamedBasicResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOwnerArchiveExternalStreamedBasicChannel : DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.IServiceOwnerArchiveExternalStreamedBasic, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOwnerArchiveExternalStreamedBasicClient : System.ServiceModel.ClientBase<DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.IServiceOwnerArchiveExternalStreamedBasic>, DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.IServiceOwnerArchiveExternalStreamedBasic {
        
        public ServiceOwnerArchiveExternalStreamedBasicClient() {
        }
        
        public ServiceOwnerArchiveExternalStreamedBasicClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOwnerArchiveExternalStreamedBasicClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOwnerArchiveExternalStreamedBasicClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOwnerArchiveExternalStreamedBasicClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.TestResponse DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.IServiceOwnerArchiveExternalStreamedBasic.Test(DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.TestRequest request) {
            return base.Channel.Test(request);
        }
        
        public void Test() {
            DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.TestRequest inValue = new DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.TestRequest();
            DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.TestResponse retVal = ((DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.IServiceOwnerArchiveExternalStreamedBasic)(this)).Test(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.TestResponse> DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.IServiceOwnerArchiveExternalStreamedBasic.TestAsync(DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.TestRequest request) {
            return base.Channel.TestAsync(request);
        }
        
        public System.Threading.Tasks.Task<DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.TestResponse> TestAsync() {
            DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.TestRequest inValue = new DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.TestRequest();
            return ((DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.IServiceOwnerArchiveExternalStreamedBasic)(this)).TestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.GetAttachmentDataStreamedBasicResponse DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.IServiceOwnerArchiveExternalStreamedBasic.GetAttachmentDataStreamedBasic(DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.GetAttachmentDataStreamedBasicRequest request) {
            return base.Channel.GetAttachmentDataStreamedBasic(request);
        }
        
        public byte[] GetAttachmentDataStreamedBasic(string systemUserName, string systemPassword, int attachmentId) {
            DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.GetAttachmentDataStreamedBasicRequest inValue = new DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.GetAttachmentDataStreamedBasicRequest();
            inValue.Body = new DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.GetAttachmentDataStreamedBasicRequestBody();
            inValue.Body.systemUserName = systemUserName;
            inValue.Body.systemPassword = systemPassword;
            inValue.Body.attachmentId = attachmentId;
            DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.GetAttachmentDataStreamedBasicResponse retVal = ((DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.IServiceOwnerArchiveExternalStreamedBasic)(this)).GetAttachmentDataStreamedBasic(inValue);
            return retVal.Body.GetAttachmentDataStreamedBasicResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.GetAttachmentDataStreamedBasicResponse> DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.IServiceOwnerArchiveExternalStreamedBasic.GetAttachmentDataStreamedBasicAsync(DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.GetAttachmentDataStreamedBasicRequest request) {
            return base.Channel.GetAttachmentDataStreamedBasicAsync(request);
        }
        
        public System.Threading.Tasks.Task<DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.GetAttachmentDataStreamedBasicResponse> GetAttachmentDataStreamedBasicAsync(string systemUserName, string systemPassword, int attachmentId) {
            DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.GetAttachmentDataStreamedBasicRequest inValue = new DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.GetAttachmentDataStreamedBasicRequest();
            inValue.Body = new DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.GetAttachmentDataStreamedBasicRequestBody();
            inValue.Body.systemUserName = systemUserName;
            inValue.Body.systemPassword = systemPassword;
            inValue.Body.attachmentId = attachmentId;
            return ((DownloadQueueExampleClient.ServiceOwnerArchiveExternalStreamed.IServiceOwnerArchiveExternalStreamedBasic)(this)).GetAttachmentDataStreamedBasicAsync(inValue);
        }
    }
}
