//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://seres.no/xsd/Kursdomene/LånesøknadJME_M/2011")]
[System.Xml.Serialization.XmlRootAttribute("melding", Namespace="http://seres.no/xsd/Kursdomene/LånesøknadJME_M/2011", IsNullable=false)]
public partial class LånesøknadJME_M {
    
    private Innsender innsenderField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    public Innsender Innsender {
        get {
            return this.innsenderField;
        }
        set {
            this.innsenderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://seres.no/xsd/Kursdomene/LånesøknadJME_M/2011")]
public partial class Innsender {
    
    private Søker søkerField;
    
    /// <remarks/>
    public Søker søker {
        get {
            return this.søkerField;
        }
        set {
            this.søkerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://seres.no/xsd/Kursdomene/LånesøknadJME_M/2011")]
public partial class Søker {
    
    private string fødselsnummerField;
    
    private string navnField;
    
    /// <remarks/>
    public string fødselsnummer {
        get {
            return this.fødselsnummerField;
        }
        set {
            this.fødselsnummerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string navn {
        get {
            return this.navnField;
        }
        set {
            this.navnField = value;
        }
    }
}
